# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks


# Setup
title:            Paige Finkelstein
tagline:          'personal site'
description:      ""
url:              
baseurl:          https://bolducp.github.io/paigefink.github.io/


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://bolducp.github.io/paigefink.github.io/
