# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks


# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      ""
url:              http://hyde.getpoole.com
baseurl:          https://bolducp.github.io/contact.html

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
